server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: POSTGRESQL
    defer-datasource-initialization: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://genesis-revature.cyh5jpqvxggt.us-west-2.rds.amazonaws.com:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: username
  h2:
    console.enabled: true
