server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: ${db-url}
    driver-class-name: org.postgresql.Driver
    username: ${db-user}
    password: ${db-pwd}
  h2:
    console.enabled: true
